<?php

declare(strict_types=1);

/**
 * @file
 * Provides a reservation entity type.
 */

use Drupal\Core\Render\Element;


/**
 * Prepares variables for reservation templates.
 *
 * Default template: jnavi-reservation.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the reservation information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_jnavi_reservation(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}



